import type { Phone, Accessory, StoreWallet } from '../types';

export const SAMPLE_PHONES: Phone[] = [
  {
    id: 'demo_ph_iphone15pm',
    name: 'Apple iPhone 15 Pro Max',
    brand: 'Apple',
    model: 'iPhone 15 Pro Max',
    condition: 'new',
    imei1: '356789123456781',
    imei2: '356789123456782',
    storage: '256GB',
    color: 'تيتانيوم طبيعي (Natural Titanium)',
    batteryHealth: 100,
    hasBox: true,
    hasOriginalAccessories: true,
    costPrice: 54000,
    minSellPrice: 57500,
    sellPrice: 58900,
    status: 'available',
    createdAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    notes: 'جديد متبرشم بضمان دولي',
  },
  {
    id: 'demo_ph_iphone13p',
    name: 'Apple iPhone 13 Pro',
    brand: 'Apple',
    model: 'iPhone 13 Pro',
    condition: 'used',
    imei1: '354321098765431',
    imei2: '354321098765432',
    storage: '128GB',
    color: 'أزرق سييرا (Sierra Blue)',
    batteryHealth: 88,
    physicalCondition: 'كسر زيرو - بدون أي خدوش أو صيانات سابقة',
    hasBox: true,
    hasOriginalAccessories: false,
    costPrice: 28000,
    minSellPrice: 30500,
    sellPrice: 31900,
    status: 'available',
    sellerInfo: {
      name: 'محمود عبد الرحمن السيد',
      nationalId: '29508151234567',
      phone: '01012345678',
      notes: 'تم فحص الهاتف بالكامل والأيسيهات أصلية',
    },
    createdAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'demo_ph_s24ultra',
    name: 'Samsung Galaxy S24 Ultra 5G',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    condition: 'new',
    imei1: '358912345678901',
    imei2: '358912345678902',
    storage: '512GB',
    color: 'رمادي تيتانيوم (Titanium Gray)',
    batteryHealth: 100,
    hasBox: true,
    hasOriginalAccessories: true,
    costPrice: 48000,
    minSellPrice: 51000,
    sellPrice: 52500,
    status: 'available',
    createdAt: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    notes: 'نسخة الشرق الأوسط مع دعم الذكاء الاصطناعي Galaxy AI',
  },
  {
    id: 'demo_ph_redmi13pro',
    name: 'Xiaomi Redmi Note 13 Pro 4G',
    brand: 'Xiaomi',
    model: 'Redmi Note 13 Pro',
    condition: 'new',
    imei1: '864512061234561',
    imei2: '864512061234562',
    storage: '256GB / 8GB RAM',
    color: 'أسود منتصف الليل (Midnight Black)',
    batteryHealth: 100,
    hasBox: true,
    hasOriginalAccessories: true,
    costPrice: 10500,
    minSellPrice: 11600,
    sellPrice: 12200,
    status: 'available',
    createdAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    notes: 'كاميرا 200 ميجابكسل وشاحن 67 واط داخل العلبة',
  },
  {
    id: 'demo_ph_a54',
    name: 'Samsung Galaxy A54 5G',
    brand: 'Samsung',
    model: 'Galaxy A54',
    condition: 'used',
    imei1: '359123456789012',
    storage: '128GB / 8GB RAM',
    color: 'أخضر ليموني رائع (Awesome Lime)',
    batteryHealth: 94,
    physicalCondition: 'استخدام خفيف جداً شهرين فقط بحالة الفابريكة',
    hasBox: true,
    hasOriginalAccessories: true,
    costPrice: 8500,
    minSellPrice: 9600,
    sellPrice: 10200,
    status: 'available',
    sellerInfo: {
      name: 'كريم حسن علي',
      nationalId: '29810201402231',
      phone: '01122334455',
    },
    createdAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
  },
];

export const SAMPLE_ACCESSORIES: Accessory[] = [
  {
    id: 'demo_acc_apple20w',
    name: 'شاحن أبل أصلي Apple 20W USB-C',
    category: 'شواحن',
    barcode: '194252157004',
    costPrice: 450,
    sellPriceRetail: 650,
    sellPriceWholesale: 550,
    stockQuantity: 25,
    minStockAlert: 5,
    location: 'رف الشواحن A1',
    hasVariants: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_acc_magsafe_case',
    name: 'جراب MagSafe مغناطيسي مضاد للصدمات',
    category: 'جرابات',
    barcode: '693210984501',
    costPrice: 75,
    sellPriceRetail: 180,
    sellPriceWholesale: 120,
    stockQuantity: 32,
    minStockAlert: 8,
    location: 'ستاند الكفرات B2',
    hasVariants: true,
    variants: [
      { id: 'v_ip15pm', name: 'iPhone 15 Pro Max (شفاف)', stockQuantity: 12 },
      { id: 'v_ip15p', name: 'iPhone 15 Pro (أسود تيتانيوم)', stockQuantity: 8 },
      { id: 'v_ip13p', name: 'iPhone 13 Pro (كحلي مطفي)', stockQuantity: 7 },
      { id: 'v_s24u', name: 'Galaxy S24 Ultra (رمادي غامق)', stockQuantity: 5 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_acc_anker_cable',
    name: 'كابل Anker PowerLine Type-C to Type-C 60W',
    category: 'كابلات',
    barcode: '194644081234',
    costPrice: 120,
    sellPriceRetail: 220,
    sellPriceWholesale: 170,
    stockQuantity: 40,
    minStockAlert: 10,
    location: 'درج الكابلات C1',
    hasVariants: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_acc_screen_protector',
    name: 'اسكرينة حماية زجاجية سيراميك 9D ضد البصمات',
    category: 'سكرينات',
    barcode: '692134567890',
    costPrice: 25,
    sellPriceRetail: 75,
    sellPriceWholesale: 45,
    stockQuantity: 50,
    minStockAlert: 15,
    location: 'دولاب الاسكرينات D3',
    hasVariants: true,
    variants: [
      { id: 'sc_15pm', name: 'iPhone 15 Pro Max', stockQuantity: 20 },
      { id: 'sc_13p', name: 'iPhone 13 / 13 Pro', stockQuantity: 15 },
      { id: 'sc_s24u', name: 'Samsung S24 Ultra', stockQuantity: 15 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_acc_joyroom_anc',
    name: 'سماعة Joyroom JR-T03S Pro (ANC عزل ضوضاء)',
    category: 'سماعات',
    barcode: '694123789012',
    costPrice: 650,
    sellPriceRetail: 950,
    sellPriceWholesale: 800,
    stockQuantity: 12,
    minStockAlert: 3,
    location: 'فاترينة السماعات E1',
    hasVariants: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_acc_remax_powerbank',
    name: 'باور بانك Remax 20000mAh 22.5W شحن سريع',
    category: 'باور بنك',
    barcode: '695432109876',
    costPrice: 550,
    sellPriceRetail: 850,
    sellPriceWholesale: 700,
    stockQuantity: 8,
    minStockAlert: 2,
    location: 'فاترينة الباوربانك E2',
    hasVariants: false,
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_WALLETS: StoreWallet[] = [
  {
    id: 'demo_wlt_vodafone_primary',
    name: 'فودافون كاش - الأساسي (01012345678)',
    type: 'vodafone',
    phoneNumberOrAccount: '01012345678',
    balance: 15000,
    color: '#e60000',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_wlt_vodafone_secondary',
    name: 'فودافون كاش - تحويل سريع (01098765432)',
    type: 'vodafone',
    phoneNumberOrAccount: '01098765432',
    balance: 8500,
    color: '#b30000',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_wlt_instapay',
    name: 'إنستاباي InstaPay - حساب المحل البنكي',
    type: 'instapay',
    phoneNumberOrAccount: '3amoryphone@instapay',
    balance: 25000,
    color: '#7b1fa2',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'demo_wlt_orange',
    name: 'أورنج كاش Orange Cash (01223344556)',
    type: 'orange',
    phoneNumberOrAccount: '01223344556',
    balance: 5000,
    color: '#ff6600',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];
